---
title: "p8105_hw1_qw2331"
output: github_document
---

I'm an R Markdown document! 

## Problem 1

Import necessary packages

```{r message =  FALSE}
library(tibble)
library(tidyverse)
```


Create a sequence of variables first

```{r}
set.seed(1234)

vec_numeric <-  rnorm(10)
vec_logic <-  c(vec_numeric > 0)
vec_char <-  vector("character", length = 10)
vec_factor <- factor(c("a", "a", "b", "c", "b", "c", "a", "b", "b", "c"))
```


Form a data frame using the *`tibble`* function and display

```{r}
mydataframe <-  tibble(
  vec_numeric, 
  vec_logic, 
  vec_char, 
  vec_factor)

mydataframe
```


Calculate the mean of each variable using the *`pull`* function

```{r warning = FALSE}
for (i in names(mydataframe)) {
  cat("The mean of", i, "is ", mean(pull(mydataframe, i)), "\n")
}
```


Apply the `as.numeric` function to the logical, character and factor variables

```{r results = "hide"}
for (i in names(mydataframe)[c(2:4)]) {
  cat("Converting", i, "to", as.numeric(pull(mydataframe, i)), "\n")
}
```

